---
services:

  web:
    git: git@github.com:cloud66-samples/rails-psql-redis.git
    git_branch: master
    command: bundle exec rails s _env:_env:RAILS_ENV
    ports: 
      - 3000:80:443
    env_vars:
      RAILS_ENV: production
      RACK_ENV: production

  worker:
    git: git@github.com:cloud66-samples/rails-psql-redis.git
    git_branch: master
    command: bundle exec rake test:work
    
    env_vars:
      RAILS_ENV: production
      RACK_ENV: production

  scheduler:
    git: git@github.com:cloud66-samples/rails-psql-redis.git
    git_branch: master
    command: bundle exec rake test:work
    
    env_vars:
      RAILS_ENV: production
      RACK_ENV: production

databases:
  - postgresql
  - redis
